### ISSUE TITLE
Non-Jade Syntax is Gone

### ISSUE THREAD

**Issue by gridwalk** [crisward/sublime-tag#4]
![screen shot 2016-02-29 at 11 00 13 pm](https://cloud.githubusercontent.com/assets/3262690/13420118/4c7211c2-df38-11e5-8131-2a63921e4415.png)

With the new update I've got two instances of the Jade syntax, but the original Riot syntax type is gone.

I tried removing and reinstalling the package using Package control.

**Comment by crisward** [comment]
whoops, copied the wrong content into the file... I'll update this morning

**Comment by gridwalk** [comment]
Thanks! Grateful for your work :+1:

**Comment by crisward** [comment]
I've push a new release, I tried to check this when I pushed it last night, but package control didn't update straightaway. I've been improving the syntax highlighting in VS code, because it's quicker to preview in, so I have to copy the files across for the sublime version, hence the error. 

Hope it's not wasted too much time for you, I hate it when updates break my setup!

**Comment by crisward** [comment]
10.7 is now available, I'll close this now.
